---

- name: Set Login Window Text
  osx_defaults:
    domain: com.apple.loginwindow
    key: LoginwindowText
    type: string
    value: "Name: {{ full_name }} | Company: {{ company }} | Phone: {{ phone }} | Email: {{ email }}"
    state: present

- name: Disable reordering of spaces automatically
  osx_defaults:
    domain: com.apple.dock
    key: mru-spaces
    type: bool
    value: false
    state: present


- name: Disable reordering of spaces automatically
  osx_defaults:
    domain: NSGlobalDomain
    key: NSDocumentSaveNewDocumentsToCloud
    type: bool
    value: false
    state: present

- name: Disable reordering of spaces automatically
  osx_defaults:
    domain: com.apple.systempreferences
    key: NSQuitAlwaysKeepsWindows
    type: bool
    value: false
    state: present

