---

- name: Set Login Window Text
  osx_defaults:
    domain: com.apple.loginwindow
    key: LoginwindowText
    type: string
    value: "Name: {{ full_name }} | Company: {{ company }} | Phone: {{ phone }} | Email: {{ email }}"

- name: Disable reordering of spaces automatically
  osx_defaults:
    domain: com.apple.dock
    key: mru-spaces
    type: bool
    value: false

- name: Disable Syncing of documents to icloud
  osx_defaults:
    domain: NSGlobalDomain
    key: NSDocumentSaveNewDocumentsToCloud
    type: bool
    value: false

- name: Disable quit always keep windows
  osx_defaults:
    domain: com.apple.systempreferences
    key: NSQuitAlwaysKeepsWindows
    type: bool
    value: false

- name: Don't write DS store files to network shares
  osx_defaults:
    domain: com.apple.desktopservices
    key: DSDontWriteNetworkStores
    type: bool
    value: true


- name: Don't write DS store files to usb devices
  osx_defaults:
    domain: com.apple.desktopservices
    key: DSDontWriteUSBStores
    type: bool
    value: true

- name: Set perms on ssh key
  file:
    path: ~/.ssh/id_rsa
    mode: '0600'

- name: Change the shell to something fishy
  shell: chsh -s /usr/local/bin/fish
