---

- hosts: localhost
  vars:
    company: Mavenlink
  vars_prompt:
    - name: full_name
      prompt: "Full name:"
      private: no

    - name: email
      prompt: "Email:"
      private: no

    - name: phone
      prompt: "Phone:"
      private: no

  roles:
    - { role: apps, tags: ["apps"] }
    - { role: flutter, tags: ["apps", "mobile"] }
    - { role: gems, tags: ["apps"] }
    - { role: mac_defaults, tags: ["mac"] }
    - { role: mac_dock, tags: ["mac"] }
    - { role: mac_keyboard, tags: ["mac"] }
    - { role: mac_menu_bar, tags: ["mac"] }
    - { role: git_config, tags: ["git"] }
