---

- name: add a prettier git log alias
  git_config:
    name: alias.lg
    state: present
    scope: global
    value: "log --color --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit"
