---

- homebrew_tap:
    name: homebrew/cask-fonts
    state: present

- name: install gui apps
  homebrew_cask:
    name: "{{ item }}"
    state: present
  register: apps_installed
  loop:
    - slack
    - authy
    - iterm2
    - jetbrains-toolbox
    - sequel-pro
    - visual-studio-code
    - zoomus
    - licecap
    - 1password
    - simplenote
    - veracrypt
    - alacritty
    - pomodone
    - insomnia
    - balenaetcher
    - chromedriver
    - brave-browser
    - amazon-music
    - lastpass

- name: install commandline apps
  homebrew:
    name: "{{ item }}"
    state: present
  register: commandline_apps_installed
  loop:
    - fish
    - exercism
    - jq

